require('dotenv').config()

export default {
  CHILDCHAIN_DEPOSIT_CONFIRMATION_BLOCKS: 12,
  CHILDCHAIN_EXIT_CONFIRMATION_BLOCKS: 12,
  ROOTCHAIN_TRANSFER_CONFIRMATION_BLOCKS: 1,
  EXIT_PERIOD: 1200000,
  ETHERSCAN_API_KEY: 'ETHERSCAN_API_KEY',
  ETHERSCAN_API_URL: 'https://api-rinkeby.etherscan.io/api/',
  ETHERSCAN_URL: 'https://rinkeby.etherscan.io/',
  ETHEREUM_NETWORK: 'rinkeby',
  OMISEGO_NETWORK: 'rinkeby',
  WEB3_HTTP_PROVIDER: 'WEB3_HTTP_PROVIDER',
  PLASMA_FRAMEWORK_CONTRACT_ADDRESS: 'PLASMA_FRAMEWORK_CONTRACT_ADDRESS',
  PLASMA_PAYMENT_EXIT_GAME_CONTRACT_ADDRESS:
    'PLASMA_PAYMENT_EXIT_GAME_CONTRACT_ADDRESS',
  ETH_VAULT_CONTRACT_ADDRESS: 'ETH_VAULT_CONTRACT_ADDRESS',
  ERC20_VAULT_CONTRACT_ADDRESS: 'ERC20_VAULT_CONTRACT_ADDRESS',
  WATCHER_URL: 'WATCHER_URL',
  BLOCK_EXPLORER_URL: 'BLOCK_EXPLORER_URL',

  // For Testing
  TEST_FUND_ADDRESS: process.env.MW_TEST_FUND_ADDRESS,
  TEST_FUND_PRIVATE_KEY: process.env.MW_TEST_FUND_PRIVATE_KEY,
  TEST_ADDRESS: 'TEST_ADDRESS',
  TEST_PRIVATE_KEY: 'TEST_PRIVATE_KEY',
  TEST_ERC20_TOKEN_CONTRACT_ADDRESS: 'TEST_ERC20_TOKEN_CONTRACT_ADDRESS'
}
