version: 2

workflows:
  version: 2

  testflight-release:
    jobs:
      - mobile-wallet-build
      - fastlane-to-testflight:
          requires:
            - mobile-wallet-build

jobs:
  #
  # Mobile wallet build jobs
  #
  mobile-wallet-build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-mobile-wallet-node-modules-{{ checksum "package-lock.json" }}
      - run:
          name: Run mobile-wallet build
          command: npm install
      - save_cache:
          key: v1-mobile-wallet-node-modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          name: Persist workspace
          root: .
          paths: '.'

  fastlane-to-testflight:
    macos:
      xcode: 11.5.0 # Image manifest: https://circle-macos-docs.s3.amazonaws.com/image-manifest/v2960/index.html
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Decrypting and adding Firebase configuration file
          command: echo "$FIREBASE_CONFIG" | base64 --decode > ios/PlasmaWallet/wallet/GoogleService-Info.plist
      - run:
          name: Decrypting and adding Sentry configuration file
          command: echo "$SENTRY_CONFIG" | base64 --decode > ios/sentry.properties
      - run:
          name: Set Ruby version
          command: echo 'chruby ruby-2.6.6' >> ~/.bash_profile
      - restore_cache:
          name: Restoring cache (Ruby)
          key: 1-gems-{{ checksum "ios/Gemfile.lock" }}
      - run:
          name: Installing Ruby dependencies
          command: |
            cd ios
            sudo gem install bundler && bundle config set path 'vendor/bundle' && bundle install
      - save_cache:
          name: Saving cache (Ruby)
          key: 1-gems-{{ checksum "ios/Gemfile.lock" }}
          paths:
            - 'ios/vendor/bundle/'
      - persist_to_workspace:
          name: Persisting to workspace
          root: .
          paths: 'ios/'
      - run:
          name: Installing CocoaPods
          command: |
            cd ios
            bundle exec pod install
      - run:
          name: Running Fastlane
          command: |
            cd ios
            bundle exec fastlane testflight_ci
