# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  skip_docs
  
  desc "Push a new build to TestFlight (local)"
  lane :testflight_local do
    clear_derived_data
    match(type: "appstore")
    increment_build_number(
      build_number: latest_testflight_build_number(
        initial_build_number: 1,
        version: get_version_number(xcodeproj: "PlasmaWallet.xcodeproj", target: "PlasmaWallet")
      ) + 1
    )
    build_ios_app(scheme: "PlasmaWallet", clean: true)
    upload_to_testflight
  end

  desc "Push a new build to TestFlight (CI)"
  lane :testflight_ci do
    xcversion("11.2.0")
    match(type: "appstore")
    increment_build_number(
      build_number: latest_testflight_build_number(
        initial_build_number: 1,
        version: get_version_number(xcodeproj: "PlasmaWallet.xcodeproj", target: "PlasmaWallet")
      ) + 1
    )
    build_ios_app(scheme: "PlasmaWallet")
    upload_to_testflight
  end
end
