# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  skip_docs

  desc "Push a new beta build to TestFlight"
  lane :beta do
    clear_derived_data
    match(type: "appstore", readonly: is_ci)
    increment_build_number({
      build_number: 100
    })
    build_ios_app(scheme: "PlasmaWallet", clean: true)
    upload_to_testflight
  end
end
