# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end
  
  skip_docs

  desc "Push a new build to TestFlight (local)"
  lane :testflight_local do
    clear_derived_data
    update_code_signing_settings(use_automatic_signing: false)
    match(type: "appstore")
    increment_build_number(
      build_number: latest_testflight_build_number(
        initial_build_number: 1,
        version: get_version_number(xcodeproj: "PlasmaWallet.xcodeproj", target: "PlasmaWallet")
      ) + 1
    )
    build_ios_app(scheme: "PlasmaWallet", clean: true)
    upload_to_testflight
  end

  desc "Push a new build to TestFlight (CI)"
  lane :testflight_ci do
    match(type: "appstore", readonly: true)
    increment_build_number(build_number: ENV["CIRCLE_BUILD_NUM"])
    build_ios_app(scheme: "PlasmaWallet", silent: true, clean: true, include_symbols: true)
    upload_to_testflight(skip_waiting_for_build_processing: true, apple_id: ENV["APPLE_APP_ID"])
  end
end
