export const TYPE_CHILDCHAIN_SEND_TOKEN = 'CHILDCHAIN_SEND_TOKEN'
export const TYPE_CHILDCHAIN_DEPOSIT = 'CHILDCHAIN_DEPOSIT'
export const TYPE_CHILDCHAIN_EXIT = 'CHILDCHAIN_EXIT'
export const TYPE_CHILDCHAIN_READY_PROCESS_EXIT =
  'CHILDCHAIN_READY_PROCESS_EXIT'
export const TYPE_ROOTCHAIN_SEND_TOKEN = 'ROOTCHAIN_SEND_TOKEN'
export const TYPE_CHILDCHAIN_PROCESS_EXIT = 'CHILDCHAIN_PROCESS_EXIT'
export const TYPE_CHILDCHAIN_MERGE_UTXOS = 'CHILDCHAIN_MERGE_UTXOS'
